name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install ruff pytest
        uv pip install '.[dev,test,all]'
    - name: Ruff check
      run: |
        source .venv/bin/activate
        ruff check src/shadows
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest
